export const QUERIES_KEY = {
  UPLOAD_PRODUCER_PORTFOLIO: "upload producer portfolio",
  UPLOAD_VOCAL_SEARCHING: "upload producer vocal searching",
  GET_PRODUCER_PORTFOLIO_INFO: "get producer portfolio info",
  GET_TRACK_INFO: "getTrackInfo",
  GET_VOCAL_INFO: "getVocalInfo",
  GET_TRACK_COMMENT: "getComment",
  LOGOUT: "logout",
  ACCESS_TOKEN: "accessToken",
  TOKEN_VERIFY: "tokenVerify",
  TRACK_DETAIL: "trackDetail",
  TRACK_DOWNLOAD: "trackDownload",
  GET_UPLOAD_EDIT_INFO: "getUploadEditInfo",
  GET_EVENT_LIST: "getEventList",
} as const;
