export const TEXT_LIMIT = {
  TITLE_ENTER_COUNT: 2,
  INTRODUCE_ENTER_COUNT: 8,
  HASHTAG: 10,
  UPLOAD_AUDIO: 13,
  NICK_NAME: 16,
  UPLOAD_TITLE: 36,
  DESCRIPTION: 250,
  PROFILE_DESCRIPTION: 150,
};
