const comments = [
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
  {
    commentId: 18,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: true,
    vocalWavFileLength: 211,
  },
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
  {
    commentId: 5,
    vocalWavFile: "AWS S3 vocal wav file url1",
    vocalName: "보컬1",
    comment: "보컬 코멘트",
    isMe: false,
    vocalWavFileLength: 210,
  },
];

export default comments;
