export enum signUpStep {
    SIGNUP_ROLE='SIGNUP_ROLE', 
    SIGNUP_EMAIL='SIGNUP_EMAIL',
    SIGNUP_PASSWORD='SIGNUP_PASSWORD', 
    SIGNUP_NICKNAME='SIGNUP_NICKNAME', 
    SIGNUP_PROFILE='SIGNUP_PROFILE', 
    SIGNUP_SUCCESS='SIGNUP_SUCCESS',
  }
  