export enum signUpStep {
    SIGNUP_ROLE='SIGNUP_ROLE', 
    SIGNUP_EMAIL_PASSWORD='SIGNUP_EMAIL_PASSWORD',
    SIGNUP_NICKNAME_CONVENTION='SIGNUP_NICKNAME_CONVENTION', 
    SIGNUP_PROFILE='SIGNUP_PROFILE', 
    SIGNUP_SUCCESS='SIGNUP_SUCCESS',
  }
  